puts "The students of Villains Academy"
puts "___________"
puts "Dr. Hannibal Lecter"
puts "Darth Vader"
puts "Hurse Ratched"
puts "Michael Corleone"
puts "Alex DeLarge"
puts "The Wicked Witch if the West"
puts "Terminator"
puts "Freddy Krueger"
puts "The Joker"
puts "Joffrey Baratheon"
puts "Norman Bates"
